### ISSUE TITLE
G722.1 Encoder

### ISSUE THREAD

**Issue by LabMember12** [kode54/libg7221_decode#1]
Hello, I know this decoder was made long ago. Is it possible to do reversal lib for encoding to G722.1 Annex C codec though? I found official source, but it works with packed bit stream files only. I would like to know way to  encode from simple wav for modding purposes.

**Comment by kode54** [comment]
You may try your luck investigating [VGAudio](https://github.com/Thealexbarney/VGAudio), but I don't intend to make it possible to encode with this repository.

**Comment by LabMember12** [comment]
Thanks. I guess worthy to check out. I already tried default codec by Polycom, that was reason to ask for alternative.
